### ISSUE TITLE
License

### ISSUE THREAD

**Issue by matelich** [tugrul512bit/FastCollisionDetectionLib#7]
Would you consider licensing this code for commercial usage?

**Comment by tugrul512bit** [comment]
Maybe. Would MIT license be better?

**Comment by matelich** [comment]
MIT would be great!

**Comment by tugrul512bit** [comment]
Ok, license is now MIT.

**Comment by matelich** [comment]
Much appreciated! I was blown away by the article, as point cloud collisions on a lower powered PC is precisely the task I need to tackle next.
